### ISSUE TITLE
Need Shorter Translations if anyone knows French Fluently.

### ISSUE THREAD

**Issue by Jieiku** [Jieiku/abridge#108]
Any translation improvments are appreciated, but the ones below are the ones I am most interested in.

My translations to French were created using google translate and some of them may be longer than necessary.

I am looking for shorter / more concise translations of the following:

```toml
[languages.fr.translations]
Search = "Recherche"
Recent_Posts = "Messages Récents"
Powered_by = "Alimenté par"
About = "À propos"
Posts = "Des postes"
Tags = "Mots clés"
Privacy = "Confidentialité"
Sitemap = "Plan du site"
```

Also, any that are as short as they can be while still making sense, let me know, thank you.

**Comment by Keats** [comment]
```toml
[languages.fr.translations]
Search = "Recherche"
Recent_Posts = "Articles Récents"
Powered_by = 1
About = "À propos"
Posts = "Articles"
Tags = "Mots-clés"
Privacy = 2
Sitemap = "Plan du site"
```

I went with "Articles" for posts but there's also "billet" which is popular.

1. a bit tricky to translate: https://french.stackexchange.com/questions/7486/an-equivalent-to-powered-by-in-software Propulsé is probably the most recognizable because of Wordpress
2. Do you mean Privacy Policy? If so then Politique de confidentialité
