### ISSUE TITLE
Which release is the most compatible for Cloudflare deployments?

### ISSUE THREAD

**Issue by IPlayZed** [Jieiku/abridge#190]
Hi!

I am using this theme on my site and I really like it.
I am doing Cloudflare deployments, but it uses Zola version 0.17.2.
Which release or commit do you think is the best suited for that version?

Thank you for the help! 😄

**Comment by Hysterelius** [comment]
I personally use Github CI to build my website before deploying it Cloudflare Pages, which I assume what you mean. This means I can choose which version of Zola I run.

For abridge, I would recommend the last major version it should work with Zola and be up to date.

This is my own Github action which builds the site and deploys it:
```yml
# .github/workflow/main.yml
on: 
  push:
    branches:
      - main
name: Build Zola website
jobs:
  build-bundle-deploy:
    runs-on: ubuntu-latest
    steps:
      # Check-out repository under $GITHUB_WORKSPACE
      - name: Checkout 📋
        uses: actions/checkout@v3
        with:
          submodules: true
      # Build static pages w/ Zola
      - name: Build 🏗️
        uses: shalzz/zola-deploy-action@v0.19.1
        env:
          BUILD_ONLY: true
        # Deploy to Cloudflare Pages
      - name: Deploy 🚀
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.PROJECT_NAME }}
          directory: public
```

Just pop this file in `.github/workflows/main.yml` and add your secrets into the repository and you should be all good ☺️
