### ISSUE TITLE
Next/Prev Buttons

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#77]
2 small issues:

1- Links do not have a discernible name when using fontawesome, I think this means there is not `alt` value?
![2022-06-21_06-47](https://user-images.githubusercontent.com/48108917/174782395-403979b7-f2b6-4bb8-a2b2-3111d8de4673.png)

2- Pagination icons are not properly centered
![2022-06-21_06-30](https://user-images.githubusercontent.com/48108917/174782561-97f12171-cb3f-49a4-b8d4-a1358a51057b.png)

**Comment by Jieiku** [comment]
Adding the Alt names is easy, will do that today.

The centering of those icons is a font issue. I tried for an hour to center them, and in the end was unable to but didn't think they looked that bad. The only thing I can think to do is just rip them out to svg files and add them as icons to Abridge, will try doing that today.

**Comment by simbleau** [comment]
Disregard the font issue- I can choose another icon ;)

**Comment by Jieiku** [comment]
I am actually considering doing something like this for abridge: https://blog.webjeda.com/optimize-fontawesome/

The problem now is that by doing a deferred load of FontAwesome, we get a good page load score, but that is not all that is important for user experience, clicking page to page you will often see a page flicker, especially on desktop chromium. The only way around this is to NOT defer the loading of FontAwesome, but because FontAwesome is absolutely massive that is not a good idea.

The solution I think is to create a custom Bundle with only the Icons that we need.

**Comment by Jieiku** [comment]
I figured out a solution by playing tricks with the padding, will push the fix soonish.

**Comment by Jieiku** [comment]
Here is what it looks like without the Icons defined now:

![2022-06-21_18-48-50](https://user-images.githubusercontent.com/106644/174925864-a0d184ac-ab5e-4be3-841b-38917fe823c1.png)

**Comment by Jieiku** [comment]
Should be Fixed now, let me know if you see any other issues, thanks.

**Comment by Jieiku** [comment]
Abridge now has its own Icon Font based on Font Awesome, it includes 6 icon fonts:
(additionally I reworked the search icon to very closely resemble the search icon from fontawesome)

```toml
icon_search = "svgs search" # Search button in search box.
icon_adjust = "svgs svgh i-adjust" # Theme Switcher button in top menu.
icon_top = "svgs i-up" # Back to Top Button.
icon_first = "svgs i-first" # Pagination First Page.
icon_prev = "svgs i-prev" # Pagination Previous Page.
icon_next = "svgs i-next" # Pagination Next Page.
icon_last = "svgs i-last" # Pagination Last Page.
```


https://abridge.netlify.app/
